// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6f3s9HsYJ7D2ZXLM5AbnsTXdIHU-jJ64',
    appId: '1:138021089357:web:239c8ec25e89ddfeaa2c04',
    messagingSenderId: '138021089357',
    projectId: 'my-cart-dbef5',
    authDomain: 'my-cart-dbef5.firebaseapp.com',
    storageBucket: 'my-cart-dbef5.appspot.com',
    measurementId: 'G-S675V45LBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEplQzKard6iarxDPkmFGwbVoI1YK46K8',
    appId: '1:138021089357:android:c361007f160972c4aa2c04',
    messagingSenderId: '138021089357',
    projectId: 'my-cart-dbef5',
    storageBucket: 'my-cart-dbef5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnpOw0XDuR8Z092gQYbzKMVCrb07dJ1qA',
    appId: '1:138021089357:ios:3e2cdce996239a3aaa2c04',
    messagingSenderId: '138021089357',
    projectId: 'my-cart-dbef5',
    storageBucket: 'my-cart-dbef5.appspot.com',
    androidClientId: '138021089357-b6gh5auhnh8tfgh0ebnr2gdt6j7kkfml.apps.googleusercontent.com',
    iosClientId: '138021089357-nvj76kor0gsq27ig8mvvmj0r2efnoh80.apps.googleusercontent.com',
    iosBundleId: 'com.example.mCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnpOw0XDuR8Z092gQYbzKMVCrb07dJ1qA',
    appId: '1:138021089357:ios:439bdaa95c70b5ffaa2c04',
    messagingSenderId: '138021089357',
    projectId: 'my-cart-dbef5',
    storageBucket: 'my-cart-dbef5.appspot.com',
    androidClientId: '138021089357-b6gh5auhnh8tfgh0ebnr2gdt6j7kkfml.apps.googleusercontent.com',
    iosClientId: '138021089357-cn3nv0rahn0gj6o5shud6fbd071ncrhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mCart.RunnerTests',
  );
}
